/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnouncementsGetAnnouncementsListResponse {
    #[serde(rename = "announcements", skip_serializing_if = "Option::is_none")]
    pub announcements: Option<Vec<models::AnnouncementsGetAnnouncementResponse>>,
}

impl AnnouncementsGetAnnouncementsListResponse {
    pub fn new() -> AnnouncementsGetAnnouncementsListResponse {
        AnnouncementsGetAnnouncementsListResponse {
            announcements: None,
        }
    }
}
