/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnouncementsGetAnnouncementResponse {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "start_time")]
    pub start_time: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "end_time")]
    pub end_time: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "publishable")]
    pub publishable: bool,
}

impl AnnouncementsGetAnnouncementResponse {
    pub fn new(
        id: i32,
        title: String,
        content: String,
        start_time: chrono::DateTime<chrono::FixedOffset>,
        end_time: chrono::DateTime<chrono::FixedOffset>,
        publishable: bool,
    ) -> AnnouncementsGetAnnouncementResponse {
        AnnouncementsGetAnnouncementResponse {
            id,
            title,
            content,
            start_time,
            end_time,
            publishable,
        }
    }
}
