/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTokenApiTokenStatus {
    /// The expiration date of the api token
    #[serde(
        rename = "api_token_expiration",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_token_expiration: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ApiTokenApiTokenStatus {
    pub fn new() -> ApiTokenApiTokenStatus {
        ApiTokenApiTokenStatus {
            api_token_expiration: None,
        }
    }
}
