/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTokenApiToken {
    /// The api token id
    #[serde(rename = "api_token_id", skip_serializing_if = "Option::is_none")]
    pub api_token_id: Option<String>,
    /// The api token secret
    #[serde(rename = "api_token_secret", skip_serializing_if = "Option::is_none")]
    pub api_token_secret: Option<String>,
    /// The expiration date of the api token
    #[serde(
        rename = "api_token_expiration",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_token_expiration: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ApiTokenApiToken {
    pub fn new() -> ApiTokenApiToken {
        ApiTokenApiToken {
            api_token_id: None,
            api_token_secret: None,
            api_token_expiration: None,
        }
    }
}
