/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevicesDeviceInfo {
    #[serde(rename = "device_id")]
    pub device_id: String,
    #[serde(rename = "device_type")]
    pub device_type: DeviceType,
    #[serde(rename = "status")]
    pub status: Status,
    /// Parameter mandatory and valid for 'unavailable' devices
    #[serde(rename = "available_at", skip_serializing_if = "Option::is_none")]
    pub available_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "n_pending_jobs")]
    pub n_pending_jobs: i32,
    #[serde(rename = "n_qubits", skip_serializing_if = "Option::is_none")]
    pub n_qubits: Option<i32>,
    #[serde(rename = "basis_gates")]
    pub basis_gates: Vec<String>,
    #[serde(rename = "supported_instructions")]
    pub supported_instructions: Vec<String>,
    /// json format calibration_data and n_nodes etc
    #[serde(rename = "device_info", skip_serializing_if = "Option::is_none")]
    pub device_info: Option<String>,
    /// Parameter available only for `QPU` devices with available calibration data
    #[serde(rename = "calibrated_at", skip_serializing_if = "Option::is_none")]
    pub calibrated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "description")]
    pub description: String,
}

impl DevicesDeviceInfo {
    pub fn new(
        device_id: String,
        device_type: DeviceType,
        status: Status,
        n_pending_jobs: i32,
        basis_gates: Vec<String>,
        supported_instructions: Vec<String>,
        description: String,
    ) -> DevicesDeviceInfo {
        DevicesDeviceInfo {
            device_id,
            device_type,
            status,
            available_at: None,
            n_pending_jobs,
            n_qubits: None,
            basis_gates,
            supported_instructions,
            device_info: None,
            calibrated_at: None,
            description,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeviceType {
    #[serde(rename = "QPU")]
    Qpu,
    #[serde(rename = "simulator")]
    Simulator,
}

impl Default for DeviceType {
    fn default() -> DeviceType {
        Self::Qpu
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "available")]
    Available,
    #[serde(rename = "unavailable")]
    Unavailable,
}

impl Default for Status {
    fn default() -> Status {
        Self::Available
    }
}
