/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobsRegisteredJob : Represents a newly registered quantum job.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsRegisteredJob {
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "job_type", skip_serializing_if = "Option::is_none")]
    pub job_type: Option<models::JobsJobType>,
    #[serde(rename = "status")]
    pub status: models::JobsJobStatus,
    #[serde(rename = "device_id", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
    #[serde(rename = "shots", skip_serializing_if = "Option::is_none")]
    pub shots: Option<i32>,
    #[serde(rename = "job_info", skip_serializing_if = "Option::is_none")]
    pub job_info: Option<Box<models::JobsJobInfo>>,
    #[serde(rename = "transpiler_info", skip_serializing_if = "Option::is_none")]
    pub transpiler_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "simulator_info", skip_serializing_if = "Option::is_none")]
    pub simulator_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "mitigation_info", skip_serializing_if = "Option::is_none")]
    pub mitigation_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "execution_time", skip_serializing_if = "Option::is_none")]
    pub execution_time: Option<f64>,
    #[serde(rename = "submitted_at", skip_serializing_if = "Option::is_none")]
    pub submitted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "ready_at", skip_serializing_if = "Option::is_none")]
    pub ready_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "running_at", skip_serializing_if = "Option::is_none")]
    pub running_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "ended_at", skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl JobsRegisteredJob {
    /// Represents a newly registered quantum job.
    pub fn new(job_id: String, status: models::JobsJobStatus) -> JobsRegisteredJob {
        JobsRegisteredJob {
            job_id,
            name: None,
            description: None,
            job_type: None,
            status,
            device_id: None,
            shots: None,
            job_info: None,
            transpiler_info: None,
            simulator_info: None,
            mitigation_info: None,
            execution_time: None,
            submitted_at: None,
            ready_at: None,
            running_at: None,
            ended_at: None,
        }
    }
}
