/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsS3OperatorItem {
    /// The Pauli string.
    #[serde(rename = "pauli")]
    pub pauli: String,
    /// Coefficient number in the Pauli string representation.
    #[serde(rename = "coeff", skip_serializing_if = "Option::is_none")]
    pub coeff: Option<f64>,
}

impl JobsS3OperatorItem {
    pub fn new(pauli: String) -> JobsS3OperatorItem {
        JobsS3OperatorItem { pauli, coeff: None }
    }
}
