/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobsJobInfoUploadPresignedUrl : Presigned URL for uploading file to OCTOPUS cloud.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsJobInfoUploadPresignedUrl {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "fields")]
    pub fields: Box<models::JobsJobInfoUploadPresignedUrlFields>,
}

impl JobsJobInfoUploadPresignedUrl {
    /// Presigned URL for uploading file to OCTOPUS cloud.
    pub fn new(
        url: String,
        fields: models::JobsJobInfoUploadPresignedUrlFields,
    ) -> JobsJobInfoUploadPresignedUrl {
        JobsJobInfoUploadPresignedUrl {
            url,
            fields: Box::new(fields),
        }
    }
}
