/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobsGetJobStatusResponse : job status
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsGetJobStatusResponse {
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "status")]
    pub status: models::JobsJobStatus,
}

impl JobsGetJobStatusResponse {
    /// job status
    pub fn new(job_id: String, status: models::JobsJobStatus) -> JobsGetJobStatusResponse {
        JobsGetJobStatusResponse { job_id, status }
    }
}
