/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobsRegisterJobResponse : Register new job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsRegisterJobResponse {
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "presigned_url")]
    pub presigned_url: Box<models::JobsJobInfoUploadPresignedUrl>,
}

impl JobsRegisterJobResponse {
    /// Register new job
    pub fn new(
        job_id: String,
        presigned_url: models::JobsJobInfoUploadPresignedUrl,
    ) -> JobsRegisterJobResponse {
        JobsRegisterJobResponse {
            job_id,
            presigned_url: Box::new(presigned_url),
        }
    }
}
