/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsJobInfoUploadPresignedUrlFields {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "AWSAccessKeyId", skip_serializing_if = "Option::is_none")]
    pub aws_access_key_id: Option<String>,
    #[serde(
        rename = "x-amz-security-token",
        skip_serializing_if = "Option::is_none"
    )]
    pub x_amz_security_token: Option<String>,
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<String>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

impl JobsJobInfoUploadPresignedUrlFields {
    pub fn new(key: String) -> JobsJobInfoUploadPresignedUrlFields {
        JobsJobInfoUploadPresignedUrlFields {
            key,
            aws_access_key_id: None,
            x_amz_security_token: None,
            policy: None,
            signature: None,
        }
    }
}
