/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobsJobInfo : Presigned URLs for downloading relevant job information .zip files from OQTOPUS cloud.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsJobInfo {
    /// Content of the file will match `jobs.S3SubmitJobInfo` schema.
    #[serde(rename = "input")]
    pub input: String,
    /// For multiprogramming jobs, this file contains the combined circuit.
    #[serde(rename = "combined_program", skip_serializing_if = "Option::is_none")]
    pub combined_program: Option<String>,
    /// Content of the file will match `jobs.S3JobResult` schema.
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<String>,
    /// Content of the file will match `jobs.S3TranspileResult` schema.
    #[serde(rename = "transpile_result", skip_serializing_if = "Option::is_none")]
    pub transpile_result: Option<String>,
    /// File available only for sse jobs.
    #[serde(rename = "sse_log", skip_serializing_if = "Option::is_none")]
    pub sse_log: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl JobsJobInfo {
    /// Presigned URLs for downloading relevant job information .zip files from OQTOPUS cloud.
    pub fn new(input: String) -> JobsJobInfo {
        JobsJobInfo {
            input,
            combined_program: None,
            result: None,
            transpile_result: None,
            sse_log: None,
            message: None,
        }
    }
}
