/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsS3SubmitJobInfo {
    /// A list of OPENQASM3 program. Required for sampling, estimation and multiprogramming jobs. For non-multiprogramming jobs, this field is assumed to contain exactly one program. Otherwise, those programs are combined according to the multiprogramming machinery.
    #[serde(rename = "program", skip_serializing_if = "Option::is_none")]
    pub program: Option<Vec<String>>,
    /// Estimation operator. Required for estimation jobs.
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<Vec<models::JobsS3OperatorItem>>,
    /// SSE user program. Required for SSE jobs.
    #[serde(rename = "sse_program", skip_serializing_if = "Option::is_none")]
    pub sse_program: Option<String>,
}

impl JobsS3SubmitJobInfo {
    pub fn new() -> JobsS3SubmitJobInfo {
        JobsS3SubmitJobInfo {
            program: None,
            operator: None,
            sse_program: None,
        }
    }
}
