/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsSubmitJobRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "device_id")]
    pub device_id: String,
    #[serde(rename = "job_type")]
    pub job_type: models::JobsJobType,
    #[serde(rename = "transpiler_info", skip_serializing_if = "Option::is_none")]
    pub transpiler_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "simulator_info", skip_serializing_if = "Option::is_none")]
    pub simulator_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "mitigation_info", skip_serializing_if = "Option::is_none")]
    pub mitigation_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "shots")]
    pub shots: i32,
}

impl JobsSubmitJobRequest {
    pub fn new(
        device_id: String,
        job_type: models::JobsJobType,
        shots: i32,
    ) -> JobsSubmitJobRequest {
        JobsSubmitJobRequest {
            name: None,
            description: None,
            device_id,
            job_type,
            transpiler_info: None,
            simulator_info: None,
            mitigation_info: None,
            shots,
        }
    }
}
