/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobsJobType {
    #[serde(rename = "estimation")]
    Estimation,
    #[serde(rename = "sampling")]
    Sampling,
    #[serde(rename = "multi_manual")]
    MultiManual,
    #[serde(rename = "sse")]
    Sse,
}

impl std::fmt::Display for JobsJobType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Estimation => write!(f, "estimation"),
            Self::Sampling => write!(f, "sampling"),
            Self::MultiManual => write!(f, "multi_manual"),
            Self::Sse => write!(f, "sse"),
        }
    }
}

impl Default for JobsJobType {
    fn default() -> JobsJobType {
        Self::Estimation
    }
}
