/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobsSubmittedJob : Represents a fully submitted quantum job.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobsSubmittedJob {
    #[serde(rename = "job_id")]
    pub job_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "job_type")]
    pub job_type: models::JobsJobType,
    #[serde(rename = "status")]
    pub status: models::JobsJobStatus,
    #[serde(rename = "device_id")]
    pub device_id: String,
    #[serde(rename = "shots")]
    pub shots: i32,
    #[serde(rename = "job_info")]
    pub job_info: Box<models::JobsJobInfo>,
    #[serde(rename = "transpiler_info", skip_serializing_if = "Option::is_none")]
    pub transpiler_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "simulator_info", skip_serializing_if = "Option::is_none")]
    pub simulator_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "mitigation_info", skip_serializing_if = "Option::is_none")]
    pub mitigation_info: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "execution_time", skip_serializing_if = "Option::is_none")]
    pub execution_time: Option<f64>,
    #[serde(rename = "submitted_at")]
    pub submitted_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "ready_at", skip_serializing_if = "Option::is_none")]
    pub ready_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "running_at", skip_serializing_if = "Option::is_none")]
    pub running_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "ended_at", skip_serializing_if = "Option::is_none")]
    pub ended_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl JobsSubmittedJob {
    /// Represents a fully submitted quantum job.
    pub fn new(
        job_id: String,
        name: String,
        job_type: models::JobsJobType,
        status: models::JobsJobStatus,
        device_id: String,
        shots: i32,
        job_info: models::JobsJobInfo,
        submitted_at: chrono::DateTime<chrono::FixedOffset>,
    ) -> JobsSubmittedJob {
        JobsSubmittedJob {
            job_id,
            name,
            description: None,
            job_type,
            status,
            device_id,
            shots,
            job_info: Box::new(job_info),
            transpiler_info: None,
            simulator_info: None,
            mitigation_info: None,
            execution_time: None,
            submitted_at,
            ready_at: None,
            running_at: None,
            ended_at: None,
        }
    }
}
