/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SettingsGetSettingsResponse : detail of settings response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsGetSettingsResponse {
    #[serde(rename = "editable_fields")]
    pub editable_fields: Vec<EditableFields>,
    #[serde(rename = "allow_deletion")]
    pub allow_deletion: bool,
    #[serde(rename = "visible_fields")]
    pub visible_fields: Vec<VisibleFields>,
    #[serde(rename = "login_history_enabled")]
    pub login_history_enabled: bool,
}

impl SettingsGetSettingsResponse {
    /// detail of settings response
    pub fn new(
        editable_fields: Vec<EditableFields>,
        allow_deletion: bool,
        visible_fields: Vec<VisibleFields>,
        login_history_enabled: bool,
    ) -> SettingsGetSettingsResponse {
        SettingsGetSettingsResponse {
            editable_fields,
            allow_deletion,
            visible_fields,
            login_history_enabled,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EditableFields {
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "organization")]
    Organization,
}

impl Default for EditableFields {
    fn default() -> EditableFields {
        Self::Name
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VisibleFields {
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "organization")]
    Organization,
    #[serde(rename = "created_at")]
    CreatedAt,
}

impl Default for VisibleFields {
    fn default() -> VisibleFields {
        Self::Id
    }
}
