/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UsersUpdateUserRequest : user update data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersUpdateUserRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
}

impl UsersUpdateUserRequest {
    /// user update data
    pub fn new() -> UsersUpdateUserRequest {
        UsersUpdateUserRequest {
            name: None,
            organization: None,
        }
    }
}
