/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UsersGetOneUserResponse : detail of user response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersGetOneUserResponse {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "organization", skip_serializing_if = "Option::is_none")]
    pub organization: Option<String>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "login_events", skip_serializing_if = "Option::is_none")]
    pub login_events: Option<Vec<models::UsersLoginEvent>>,
}

impl UsersGetOneUserResponse {
    /// detail of user response
    pub fn new() -> UsersGetOneUserResponse {
        UsersGetOneUserResponse {
            id: None,
            email: None,
            name: None,
            organization: None,
            created_at: None,
            login_events: None,
        }
    }
}
