/*
 * OQTOPUS Cloud User API
 *
 * OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: oqtopus-team[at]googlegroups.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UsersLoginEvent : details of login event
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersLoginEvent {
    #[serde(rename = "event_date", skip_serializing_if = "Option::is_none")]
    pub event_date: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "user_agent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
}

impl UsersLoginEvent {
    /// details of login event
    pub fn new() -> UsersLoginEvent {
        UsersLoginEvent {
            event_date: None,
            user_agent: None,
            ip: None,
        }
    }
}
